/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing PartnersApi
    /// </summary>
    public sealed class PartnersApiTests : ApiTestsBase
    {
        private readonly IPartnersApi _instance;

        public PartnersApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IPartnersApi>();
        }

        /// <summary>
        /// Test CreatePartner
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreatePartnerAsyncTest()
        {
            PartnerCreateDto partnerCreateDto = default!;
            var response = await _instance.CreatePartnerAsync(partnerCreateDto);
            var model = response.Created();
            Assert.IsType<PartnerResponseDto>(model);
        }

        /// <summary>
        /// Test CreatePartnerDeprecated
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreatePartnerDeprecatedAsyncTest()
        {
            Guid id = default!;
            var response = await _instance.CreatePartnerDeprecatedAsync(id);
            var model = response.Created();
            Assert.IsType<PartnerResponseDto>(model);
        }

        /// <summary>
        /// Test GetPartners
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetPartnersAsyncTest()
        {
            PartnerDirection direction = default!;
            var response = await _instance.GetPartnersAsync(direction);
            var model = response.Ok();
            Assert.IsType<List<PartnerResponseDto>>(model);
        }

        /// <summary>
        /// Test RemovePartner
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task RemovePartnerAsyncTest()
        {
            Guid id = default!;
            await _instance.RemovePartnerAsync(id);
        }

        /// <summary>
        /// Test UpdatePartner
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdatePartnerAsyncTest()
        {
            Guid id = default!;
            PartnerUpdateDto partnerUpdateDto = default!;
            var response = await _instance.UpdatePartnerAsync(id, partnerUpdateDto);
            var model = response.Ok();
            Assert.IsType<PartnerResponseDto>(model);
        }
    }
}
