/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AssetDeltaSyncDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetDeltaSyncDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetDeltaSyncDto
        //private AssetDeltaSyncDto instance;

        public AssetDeltaSyncDtoTests()
        {
            // TODO uncomment below to create an instance of AssetDeltaSyncDto
            //instance = new AssetDeltaSyncDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetDeltaSyncDto
        /// </summary>
        [Fact]
        public void AssetDeltaSyncDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetDeltaSyncDto
            //Assert.IsType<AssetDeltaSyncDto>(instance);
        }

        /// <summary>
        /// Test the property 'UpdatedAfter'
        /// </summary>
        [Fact]
        public void UpdatedAfterTest()
        {
            // TODO unit test for the property 'UpdatedAfter'
        }

        /// <summary>
        /// Test the property 'UserIds'
        /// </summary>
        [Fact]
        public void UserIdsTest()
        {
            // TODO unit test for the property 'UserIds'
        }
    }
}
