/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ManualJobName
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManualJobNameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManualJobName
        //private ManualJobName instance;

        public ManualJobNameTests()
        {
            // TODO uncomment below to create an instance of ManualJobName
            //instance = new ManualJobName();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManualJobName
        /// </summary>
        [Fact]
        public void ManualJobNameInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManualJobName
            //Assert.IsType<ManualJobName>(instance);
        }
    }
}
