/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ReverseGeocodingStateResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReverseGeocodingStateResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReverseGeocodingStateResponseDto
        //private ReverseGeocodingStateResponseDto instance;

        public ReverseGeocodingStateResponseDtoTests()
        {
            // TODO uncomment below to create an instance of ReverseGeocodingStateResponseDto
            //instance = new ReverseGeocodingStateResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReverseGeocodingStateResponseDto
        /// </summary>
        [Fact]
        public void ReverseGeocodingStateResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReverseGeocodingStateResponseDto
            //Assert.IsType<ReverseGeocodingStateResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'LastImportFileName'
        /// </summary>
        [Fact]
        public void LastImportFileNameTest()
        {
            // TODO unit test for the property 'LastImportFileName'
        }

        /// <summary>
        /// Test the property 'LastUpdate'
        /// </summary>
        [Fact]
        public void LastUpdateTest()
        {
            // TODO unit test for the property 'LastUpdate'
        }
    }
}
