/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SearchAlbumResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchAlbumResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchAlbumResponseDto
        //private SearchAlbumResponseDto instance;

        public SearchAlbumResponseDtoTests()
        {
            // TODO uncomment below to create an instance of SearchAlbumResponseDto
            //instance = new SearchAlbumResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchAlbumResponseDto
        /// </summary>
        [Fact]
        public void SearchAlbumResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchAlbumResponseDto
            //Assert.IsType<SearchAlbumResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Facets'
        /// </summary>
        [Fact]
        public void FacetsTest()
        {
            // TODO unit test for the property 'Facets'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
