/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServerApkLinksDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServerApkLinksDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServerApkLinksDto
        //private ServerApkLinksDto instance;

        public ServerApkLinksDtoTests()
        {
            // TODO uncomment below to create an instance of ServerApkLinksDto
            //instance = new ServerApkLinksDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServerApkLinksDto
        /// </summary>
        [Fact]
        public void ServerApkLinksDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServerApkLinksDto
            //Assert.IsType<ServerApkLinksDto>(instance);
        }

        /// <summary>
        /// Test the property 'Arm64v8a'
        /// </summary>
        [Fact]
        public void Arm64v8aTest()
        {
            // TODO unit test for the property 'Arm64v8a'
        }

        /// <summary>
        /// Test the property 'Armeabiv7a'
        /// </summary>
        [Fact]
        public void Armeabiv7aTest()
        {
            // TODO unit test for the property 'Armeabiv7a'
        }

        /// <summary>
        /// Test the property 'Universal'
        /// </summary>
        [Fact]
        public void UniversalTest()
        {
            // TODO unit test for the property 'Universal'
        }

        /// <summary>
        /// Test the property 'X8664'
        /// </summary>
        [Fact]
        public void X8664Test()
        {
            // TODO unit test for the property 'X8664'
        }
    }
}
