/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SessionUnlockDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionUnlockDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SessionUnlockDto
        //private SessionUnlockDto instance;

        public SessionUnlockDtoTests()
        {
            // TODO uncomment below to create an instance of SessionUnlockDto
            //instance = new SessionUnlockDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionUnlockDto
        /// </summary>
        [Fact]
        public void SessionUnlockDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SessionUnlockDto
            //Assert.IsType<SessionUnlockDto>(instance);
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'PinCode'
        /// </summary>
        [Fact]
        public void PinCodeTest()
        {
            // TODO unit test for the property 'PinCode'
        }
    }
}
