/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SyncAssetDeleteV1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SyncAssetDeleteV1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SyncAssetDeleteV1
        //private SyncAssetDeleteV1 instance;

        public SyncAssetDeleteV1Tests()
        {
            // TODO uncomment below to create an instance of SyncAssetDeleteV1
            //instance = new SyncAssetDeleteV1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SyncAssetDeleteV1
        /// </summary>
        [Fact]
        public void SyncAssetDeleteV1InstanceTest()
        {
            // TODO uncomment below to test "IsType" SyncAssetDeleteV1
            //Assert.IsType<SyncAssetDeleteV1>(instance);
        }

        /// <summary>
        /// Test the property 'AssetId'
        /// </summary>
        [Fact]
        public void AssetIdTest()
        {
            // TODO unit test for the property 'AssetId'
        }
    }
}
