/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SyncRequestType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SyncRequestTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SyncRequestType
        //private SyncRequestType instance;

        public SyncRequestTypeTests()
        {
            // TODO uncomment below to create an instance of SyncRequestType
            //instance = new SyncRequestType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SyncRequestType
        /// </summary>
        [Fact]
        public void SyncRequestTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SyncRequestType
            //Assert.IsType<SyncRequestType>(instance);
        }
    }
}
