/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SystemConfigStorageTemplateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SystemConfigStorageTemplateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SystemConfigStorageTemplateDto
        //private SystemConfigStorageTemplateDto instance;

        public SystemConfigStorageTemplateDtoTests()
        {
            // TODO uncomment below to create an instance of SystemConfigStorageTemplateDto
            //instance = new SystemConfigStorageTemplateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemConfigStorageTemplateDto
        /// </summary>
        [Fact]
        public void SystemConfigStorageTemplateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SystemConfigStorageTemplateDto
            //Assert.IsType<SystemConfigStorageTemplateDto>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'HashVerificationEnabled'
        /// </summary>
        [Fact]
        public void HashVerificationEnabledTest()
        {
            // TODO unit test for the property 'HashVerificationEnabled'
        }

        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Fact]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
    }
}
