/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TagBulkAssetsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TagBulkAssetsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TagBulkAssetsDto
        //private TagBulkAssetsDto instance;

        public TagBulkAssetsDtoTests()
        {
            // TODO uncomment below to create an instance of TagBulkAssetsDto
            //instance = new TagBulkAssetsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TagBulkAssetsDto
        /// </summary>
        [Fact]
        public void TagBulkAssetsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TagBulkAssetsDto
            //Assert.IsType<TagBulkAssetsDto>(instance);
        }

        /// <summary>
        /// Test the property 'AssetIds'
        /// </summary>
        [Fact]
        public void AssetIdsTest()
        {
            // TODO unit test for the property 'AssetIds'
        }

        /// <summary>
        /// Test the property 'TagIds'
        /// </summary>
        [Fact]
        public void TagIdsTest()
        {
            // TODO unit test for the property 'TagIds'
        }
    }
}
