/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateResponseDto
        //private TemplateResponseDto instance;

        public TemplateResponseDtoTests()
        {
            // TODO uncomment below to create an instance of TemplateResponseDto
            //instance = new TemplateResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateResponseDto
        /// </summary>
        [Fact]
        public void TemplateResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateResponseDto
            //Assert.IsType<TemplateResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Fact]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
