/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TestEmailResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestEmailResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestEmailResponseDto
        //private TestEmailResponseDto instance;

        public TestEmailResponseDtoTests()
        {
            // TODO uncomment below to create an instance of TestEmailResponseDto
            //instance = new TestEmailResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestEmailResponseDto
        /// </summary>
        [Fact]
        public void TestEmailResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestEmailResponseDto
            //Assert.IsType<TestEmailResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }
    }
}
