// <auto-generated>
/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AssetStatsResponseDto
    /// </summary>
    public partial class AssetStatsResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetStatsResponseDto" /> class.
        /// </summary>
        /// <param name="images">images</param>
        /// <param name="total">total</param>
        /// <param name="videos">videos</param>
        [JsonConstructor]
        public AssetStatsResponseDto(int images, int total, int videos)
        {
            Images = images;
            Total = total;
            Videos = videos;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Images
        /// </summary>
        [JsonPropertyName("images")]
        public int Images { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public int Total { get; set; }

        /// <summary>
        /// Gets or Sets Videos
        /// </summary>
        [JsonPropertyName("videos")]
        public int Videos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AssetStatsResponseDto {\n");
            sb.Append("  Images: ").Append(Images).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Videos: ").Append(Videos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AssetStatsResponseDto" />
    /// </summary>
    public class AssetStatsResponseDtoJsonConverter : JsonConverter<AssetStatsResponseDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="AssetStatsResponseDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AssetStatsResponseDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> images = default;
            Option<int?> total = default;
            Option<int?> videos = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "images":
                            images = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total":
                            total = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "videos":
                            videos = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!images.IsSet)
                throw new ArgumentException("Property is required for class AssetStatsResponseDto.", nameof(images));

            if (!total.IsSet)
                throw new ArgumentException("Property is required for class AssetStatsResponseDto.", nameof(total));

            if (!videos.IsSet)
                throw new ArgumentException("Property is required for class AssetStatsResponseDto.", nameof(videos));

            if (images.IsSet && images.Value == null)
                throw new ArgumentNullException(nameof(images), "Property is not nullable for class AssetStatsResponseDto.");

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class AssetStatsResponseDto.");

            if (videos.IsSet && videos.Value == null)
                throw new ArgumentNullException(nameof(videos), "Property is not nullable for class AssetStatsResponseDto.");

            return new AssetStatsResponseDto(images.Value!.Value!, total.Value!.Value!, videos.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AssetStatsResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="assetStatsResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AssetStatsResponseDto assetStatsResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, assetStatsResponseDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AssetStatsResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="assetStatsResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AssetStatsResponseDto assetStatsResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("images", assetStatsResponseDto.Images);

            writer.WriteNumber("total", assetStatsResponseDto.Total);

            writer.WriteNumber("videos", assetStatsResponseDto.Videos);
        }
    }
}
