// <auto-generated>
/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DuplicateResponseDto
    /// </summary>
    public partial class DuplicateResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DuplicateResponseDto" /> class.
        /// </summary>
        /// <param name="assets">assets</param>
        /// <param name="duplicateId">duplicateId</param>
        [JsonConstructor]
        public DuplicateResponseDto(List<AssetResponseDto> assets, string duplicateId)
        {
            Assets = assets;
            DuplicateId = duplicateId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Assets
        /// </summary>
        [JsonPropertyName("assets")]
        public List<AssetResponseDto> Assets { get; set; }

        /// <summary>
        /// Gets or Sets DuplicateId
        /// </summary>
        [JsonPropertyName("duplicateId")]
        public string DuplicateId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DuplicateResponseDto {\n");
            sb.Append("  Assets: ").Append(Assets).Append("\n");
            sb.Append("  DuplicateId: ").Append(DuplicateId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DuplicateResponseDto" />
    /// </summary>
    public class DuplicateResponseDtoJsonConverter : JsonConverter<DuplicateResponseDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="DuplicateResponseDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DuplicateResponseDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<AssetResponseDto>?> assets = default;
            Option<string?> duplicateId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "assets":
                            assets = new Option<List<AssetResponseDto>?>(JsonSerializer.Deserialize<List<AssetResponseDto>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "duplicateId":
                            duplicateId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!assets.IsSet)
                throw new ArgumentException("Property is required for class DuplicateResponseDto.", nameof(assets));

            if (!duplicateId.IsSet)
                throw new ArgumentException("Property is required for class DuplicateResponseDto.", nameof(duplicateId));

            if (assets.IsSet && assets.Value == null)
                throw new ArgumentNullException(nameof(assets), "Property is not nullable for class DuplicateResponseDto.");

            if (duplicateId.IsSet && duplicateId.Value == null)
                throw new ArgumentNullException(nameof(duplicateId), "Property is not nullable for class DuplicateResponseDto.");

            return new DuplicateResponseDto(assets.Value!, duplicateId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DuplicateResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="duplicateResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DuplicateResponseDto duplicateResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, duplicateResponseDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DuplicateResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="duplicateResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DuplicateResponseDto duplicateResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (duplicateResponseDto.Assets == null)
                throw new ArgumentNullException(nameof(duplicateResponseDto.Assets), "Property is required for class DuplicateResponseDto.");

            if (duplicateResponseDto.DuplicateId == null)
                throw new ArgumentNullException(nameof(duplicateResponseDto.DuplicateId), "Property is required for class DuplicateResponseDto.");

            writer.WritePropertyName("assets");
            JsonSerializer.Serialize(writer, duplicateResponseDto.Assets, jsonSerializerOptions);
            writer.WriteString("duplicateId", duplicateResponseDto.DuplicateId);
        }
    }
}
