// <auto-generated>
/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// QueueStatusDto
    /// </summary>
    public partial class QueueStatusDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueueStatusDto" /> class.
        /// </summary>
        /// <param name="isActive">isActive</param>
        /// <param name="isPaused">isPaused</param>
        [JsonConstructor]
        public QueueStatusDto(bool isActive, bool isPaused)
        {
            IsActive = isActive;
            IsPaused = isPaused;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [JsonPropertyName("isActive")]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets IsPaused
        /// </summary>
        [JsonPropertyName("isPaused")]
        public bool IsPaused { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueueStatusDto {\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  IsPaused: ").Append(IsPaused).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QueueStatusDto" />
    /// </summary>
    public class QueueStatusDtoJsonConverter : JsonConverter<QueueStatusDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="QueueStatusDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QueueStatusDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> isActive = default;
            Option<bool?> isPaused = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "isPaused":
                            isPaused = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!isActive.IsSet)
                throw new ArgumentException("Property is required for class QueueStatusDto.", nameof(isActive));

            if (!isPaused.IsSet)
                throw new ArgumentException("Property is required for class QueueStatusDto.", nameof(isPaused));

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class QueueStatusDto.");

            if (isPaused.IsSet && isPaused.Value == null)
                throw new ArgumentNullException(nameof(isPaused), "Property is not nullable for class QueueStatusDto.");

            return new QueueStatusDto(isActive.Value!.Value!, isPaused.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="QueueStatusDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queueStatusDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QueueStatusDto queueStatusDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, queueStatusDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QueueStatusDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queueStatusDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QueueStatusDto queueStatusDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("isActive", queueStatusDto.IsActive);

            writer.WriteBoolean("isPaused", queueStatusDto.IsPaused);
        }
    }
}
