// <auto-generated>
/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SearchFacetResponseDto
    /// </summary>
    public partial class SearchFacetResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchFacetResponseDto" /> class.
        /// </summary>
        /// <param name="counts">counts</param>
        /// <param name="fieldName">fieldName</param>
        [JsonConstructor]
        public SearchFacetResponseDto(List<SearchFacetCountResponseDto> counts, string fieldName)
        {
            Counts = counts;
            FieldName = fieldName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Counts
        /// </summary>
        [JsonPropertyName("counts")]
        public List<SearchFacetCountResponseDto> Counts { get; set; }

        /// <summary>
        /// Gets or Sets FieldName
        /// </summary>
        [JsonPropertyName("fieldName")]
        public string FieldName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchFacetResponseDto {\n");
            sb.Append("  Counts: ").Append(Counts).Append("\n");
            sb.Append("  FieldName: ").Append(FieldName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchFacetResponseDto" />
    /// </summary>
    public class SearchFacetResponseDtoJsonConverter : JsonConverter<SearchFacetResponseDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="SearchFacetResponseDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SearchFacetResponseDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<SearchFacetCountResponseDto>?> counts = default;
            Option<string?> fieldName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "counts":
                            counts = new Option<List<SearchFacetCountResponseDto>?>(JsonSerializer.Deserialize<List<SearchFacetCountResponseDto>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "fieldName":
                            fieldName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!counts.IsSet)
                throw new ArgumentException("Property is required for class SearchFacetResponseDto.", nameof(counts));

            if (!fieldName.IsSet)
                throw new ArgumentException("Property is required for class SearchFacetResponseDto.", nameof(fieldName));

            if (counts.IsSet && counts.Value == null)
                throw new ArgumentNullException(nameof(counts), "Property is not nullable for class SearchFacetResponseDto.");

            if (fieldName.IsSet && fieldName.Value == null)
                throw new ArgumentNullException(nameof(fieldName), "Property is not nullable for class SearchFacetResponseDto.");

            return new SearchFacetResponseDto(counts.Value!, fieldName.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SearchFacetResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchFacetResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SearchFacetResponseDto searchFacetResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, searchFacetResponseDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SearchFacetResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchFacetResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SearchFacetResponseDto searchFacetResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (searchFacetResponseDto.Counts == null)
                throw new ArgumentNullException(nameof(searchFacetResponseDto.Counts), "Property is required for class SearchFacetResponseDto.");

            if (searchFacetResponseDto.FieldName == null)
                throw new ArgumentNullException(nameof(searchFacetResponseDto.FieldName), "Property is required for class SearchFacetResponseDto.");

            writer.WritePropertyName("counts");
            JsonSerializer.Serialize(writer, searchFacetResponseDto.Counts, jsonSerializerOptions);
            writer.WriteString("fieldName", searchFacetResponseDto.FieldName);
        }
    }
}
