// <auto-generated>
/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines SharedLinkType
    /// </summary>
    public enum SharedLinkType
    {
        /// <summary>
        /// Enum ALBUM for value: ALBUM
        /// </summary>
        ALBUM = 1,

        /// <summary>
        /// Enum INDIVIDUAL for value: INDIVIDUAL
        /// </summary>
        INDIVIDUAL = 2
    }

    /// <summary>
    /// Converts <see cref="SharedLinkType"/> to and from the JSON value
    /// </summary>
    public static class SharedLinkTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SharedLinkType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SharedLinkType FromString(string value)
        {
            if (value.Equals("ALBUM"))
                return SharedLinkType.ALBUM;

            if (value.Equals("INDIVIDUAL"))
                return SharedLinkType.INDIVIDUAL;

            throw new NotImplementedException($"Could not convert value to type SharedLinkType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SharedLinkType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SharedLinkType? FromStringOrDefault(string value)
        {
            if (value.Equals("ALBUM"))
                return SharedLinkType.ALBUM;

            if (value.Equals("INDIVIDUAL"))
                return SharedLinkType.INDIVIDUAL;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SharedLinkType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SharedLinkType value)
        {
            if (value == SharedLinkType.ALBUM)
                return "ALBUM";

            if (value == SharedLinkType.INDIVIDUAL)
                return "INDIVIDUAL";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SharedLinkType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SharedLinkTypeJsonConverter : JsonConverter<SharedLinkType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SharedLinkType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SharedLinkType? result = rawValue == null
                ? null
                : SharedLinkTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SharedLinkType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sharedLinkType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SharedLinkType sharedLinkType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SharedLinkTypeValueConverter.ToJsonValue(sharedLinkType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SharedLinkType"/>
    /// </summary>
    public class SharedLinkTypeNullableJsonConverter : JsonConverter<SharedLinkType?>
    {
        /// <summary>
        /// Returns a SharedLinkType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SharedLinkType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SharedLinkType? result = rawValue == null
                ? null
                : SharedLinkTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SharedLinkType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sharedLinkType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SharedLinkType? sharedLinkType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(sharedLinkType.HasValue ? SharedLinkTypeValueConverter.ToJsonValue(sharedLinkType.Value).ToString() : "null");
        }
    }
}
