// <auto-generated>
/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SyncAuthUserV1
    /// </summary>
    public partial class SyncAuthUserV1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncAuthUserV1" /> class.
        /// </summary>
        /// <param name="email">email</param>
        /// <param name="hasProfileImage">hasProfileImage</param>
        /// <param name="id">id</param>
        /// <param name="isAdmin">isAdmin</param>
        /// <param name="name">name</param>
        /// <param name="oauthId">oauthId</param>
        /// <param name="profileChangedAt">profileChangedAt</param>
        /// <param name="quotaUsageInBytes">quotaUsageInBytes</param>
        /// <param name="avatarColor">avatarColor</param>
        /// <param name="deletedAt">deletedAt</param>
        /// <param name="pinCode">pinCode</param>
        /// <param name="quotaSizeInBytes">quotaSizeInBytes</param>
        /// <param name="storageLabel">storageLabel</param>
        [JsonConstructor]
        public SyncAuthUserV1(string email, bool hasProfileImage, string id, bool isAdmin, string name, string oauthId, DateTime profileChangedAt, int quotaUsageInBytes, UserAvatarColor? avatarColor = default, DateTime? deletedAt = default, string? pinCode = default, int? quotaSizeInBytes = default, string? storageLabel = default)
        {
            Email = email;
            HasProfileImage = hasProfileImage;
            Id = id;
            IsAdmin = isAdmin;
            Name = name;
            OauthId = oauthId;
            ProfileChangedAt = profileChangedAt;
            QuotaUsageInBytes = quotaUsageInBytes;
            AvatarColor = avatarColor;
            DeletedAt = deletedAt;
            PinCode = pinCode;
            QuotaSizeInBytes = quotaSizeInBytes;
            StorageLabel = storageLabel;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AvatarColor
        /// </summary>
        [JsonPropertyName("avatarColor")]
        public UserAvatarColor? AvatarColor { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets HasProfileImage
        /// </summary>
        [JsonPropertyName("hasProfileImage")]
        public bool HasProfileImage { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets IsAdmin
        /// </summary>
        [JsonPropertyName("isAdmin")]
        public bool IsAdmin { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets OauthId
        /// </summary>
        [JsonPropertyName("oauthId")]
        public string OauthId { get; set; }

        /// <summary>
        /// Gets or Sets ProfileChangedAt
        /// </summary>
        [JsonPropertyName("profileChangedAt")]
        public DateTime ProfileChangedAt { get; set; }

        /// <summary>
        /// Gets or Sets QuotaUsageInBytes
        /// </summary>
        [JsonPropertyName("quotaUsageInBytes")]
        public int QuotaUsageInBytes { get; set; }

        /// <summary>
        /// Gets or Sets DeletedAt
        /// </summary>
        [JsonPropertyName("deletedAt")]
        public DateTime? DeletedAt { get; set; }

        /// <summary>
        /// Gets or Sets PinCode
        /// </summary>
        [JsonPropertyName("pinCode")]
        public string? PinCode { get; set; }

        /// <summary>
        /// Gets or Sets QuotaSizeInBytes
        /// </summary>
        [JsonPropertyName("quotaSizeInBytes")]
        public int? QuotaSizeInBytes { get; set; }

        /// <summary>
        /// Gets or Sets StorageLabel
        /// </summary>
        [JsonPropertyName("storageLabel")]
        public string? StorageLabel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SyncAuthUserV1 {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  HasProfileImage: ").Append(HasProfileImage).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsAdmin: ").Append(IsAdmin).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OauthId: ").Append(OauthId).Append("\n");
            sb.Append("  ProfileChangedAt: ").Append(ProfileChangedAt).Append("\n");
            sb.Append("  QuotaUsageInBytes: ").Append(QuotaUsageInBytes).Append("\n");
            sb.Append("  AvatarColor: ").Append(AvatarColor).Append("\n");
            sb.Append("  DeletedAt: ").Append(DeletedAt).Append("\n");
            sb.Append("  PinCode: ").Append(PinCode).Append("\n");
            sb.Append("  QuotaSizeInBytes: ").Append(QuotaSizeInBytes).Append("\n");
            sb.Append("  StorageLabel: ").Append(StorageLabel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SyncAuthUserV1" />
    /// </summary>
    public class SyncAuthUserV1JsonConverter : JsonConverter<SyncAuthUserV1>
    {
        /// <summary>
        /// The format to use to serialize ProfileChangedAt
        /// </summary>
        public static string ProfileChangedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize DeletedAt
        /// </summary>
        public static string DeletedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="SyncAuthUserV1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SyncAuthUserV1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> email = default;
            Option<bool?> hasProfileImage = default;
            Option<string?> id = default;
            Option<bool?> isAdmin = default;
            Option<string?> name = default;
            Option<string?> oauthId = default;
            Option<DateTime?> profileChangedAt = default;
            Option<int?> quotaUsageInBytes = default;
            Option<UserAvatarColor?> avatarColor = default;
            Option<DateTime?> deletedAt = default;
            Option<string?> pinCode = default;
            Option<int?> quotaSizeInBytes = default;
            Option<string?> storageLabel = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "hasProfileImage":
                            hasProfileImage = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "isAdmin":
                            isAdmin = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "oauthId":
                            oauthId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "profileChangedAt":
                            profileChangedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "quotaUsageInBytes":
                            quotaUsageInBytes = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "avatarColor":
                            string? avatarColorRawValue = utf8JsonReader.GetString();
                            if (avatarColorRawValue != null)
                                avatarColor = new Option<UserAvatarColor?>(UserAvatarColorValueConverter.FromStringOrDefault(avatarColorRawValue));
                            break;
                        case "deletedAt":
                            deletedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "pinCode":
                            pinCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "quotaSizeInBytes":
                            quotaSizeInBytes = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "storageLabel":
                            storageLabel = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(email));

            if (!hasProfileImage.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(hasProfileImage));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(id));

            if (!isAdmin.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(isAdmin));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(name));

            if (!oauthId.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(oauthId));

            if (!profileChangedAt.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(profileChangedAt));

            if (!quotaUsageInBytes.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(quotaUsageInBytes));

            if (!avatarColor.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(avatarColor));

            if (!deletedAt.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(deletedAt));

            if (!pinCode.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(pinCode));

            if (!quotaSizeInBytes.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(quotaSizeInBytes));

            if (!storageLabel.IsSet)
                throw new ArgumentException("Property is required for class SyncAuthUserV1.", nameof(storageLabel));

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class SyncAuthUserV1.");

            if (hasProfileImage.IsSet && hasProfileImage.Value == null)
                throw new ArgumentNullException(nameof(hasProfileImage), "Property is not nullable for class SyncAuthUserV1.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class SyncAuthUserV1.");

            if (isAdmin.IsSet && isAdmin.Value == null)
                throw new ArgumentNullException(nameof(isAdmin), "Property is not nullable for class SyncAuthUserV1.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class SyncAuthUserV1.");

            if (oauthId.IsSet && oauthId.Value == null)
                throw new ArgumentNullException(nameof(oauthId), "Property is not nullable for class SyncAuthUserV1.");

            if (profileChangedAt.IsSet && profileChangedAt.Value == null)
                throw new ArgumentNullException(nameof(profileChangedAt), "Property is not nullable for class SyncAuthUserV1.");

            if (quotaUsageInBytes.IsSet && quotaUsageInBytes.Value == null)
                throw new ArgumentNullException(nameof(quotaUsageInBytes), "Property is not nullable for class SyncAuthUserV1.");

            return new SyncAuthUserV1(email.Value!, hasProfileImage.Value!.Value!, id.Value!, isAdmin.Value!.Value!, name.Value!, oauthId.Value!, profileChangedAt.Value!.Value!, quotaUsageInBytes.Value!.Value!, avatarColor.Value!, deletedAt.Value!, pinCode.Value!, quotaSizeInBytes.Value!, storageLabel.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SyncAuthUserV1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="syncAuthUserV1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SyncAuthUserV1 syncAuthUserV1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, syncAuthUserV1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SyncAuthUserV1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="syncAuthUserV1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SyncAuthUserV1 syncAuthUserV1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (syncAuthUserV1.Email == null)
                throw new ArgumentNullException(nameof(syncAuthUserV1.Email), "Property is required for class SyncAuthUserV1.");

            if (syncAuthUserV1.Id == null)
                throw new ArgumentNullException(nameof(syncAuthUserV1.Id), "Property is required for class SyncAuthUserV1.");

            if (syncAuthUserV1.Name == null)
                throw new ArgumentNullException(nameof(syncAuthUserV1.Name), "Property is required for class SyncAuthUserV1.");

            if (syncAuthUserV1.OauthId == null)
                throw new ArgumentNullException(nameof(syncAuthUserV1.OauthId), "Property is required for class SyncAuthUserV1.");

            writer.WriteString("email", syncAuthUserV1.Email);

            writer.WriteBoolean("hasProfileImage", syncAuthUserV1.HasProfileImage);

            writer.WriteString("id", syncAuthUserV1.Id);

            writer.WriteBoolean("isAdmin", syncAuthUserV1.IsAdmin);

            writer.WriteString("name", syncAuthUserV1.Name);

            writer.WriteString("oauthId", syncAuthUserV1.OauthId);

            writer.WriteString("profileChangedAt", syncAuthUserV1.ProfileChangedAt.ToString(ProfileChangedAtFormat));

            writer.WriteNumber("quotaUsageInBytes", syncAuthUserV1.QuotaUsageInBytes);

            if (syncAuthUserV1.AvatarColor == null)
                writer.WriteNull("avatarColor");
            else
            {
                var avatarColorRawValue = UserAvatarColorValueConverter.ToJsonValue(syncAuthUserV1.AvatarColor.Value);
                if (avatarColorRawValue != null)
                    writer.WriteString("avatarColor", avatarColorRawValue);
                else
                    writer.WriteNull("avatarColor");
            }

            if (syncAuthUserV1.DeletedAt != null)
                writer.WriteString("deletedAt", syncAuthUserV1.DeletedAt.Value.ToString(DeletedAtFormat));
            else
                writer.WriteNull("deletedAt");

            if (syncAuthUserV1.PinCode != null)
                writer.WriteString("pinCode", syncAuthUserV1.PinCode);
            else
                writer.WriteNull("pinCode");

            if (syncAuthUserV1.QuotaSizeInBytes != null)
                writer.WriteNumber("quotaSizeInBytes", syncAuthUserV1.QuotaSizeInBytes.Value);
            else
                writer.WriteNull("quotaSizeInBytes");

            if (syncAuthUserV1.StorageLabel != null)
                writer.WriteString("storageLabel", syncAuthUserV1.StorageLabel);
            else
                writer.WriteNull("storageLabel");
        }
    }
}
