// <auto-generated>
/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SystemConfigUserDto
    /// </summary>
    public partial class SystemConfigUserDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemConfigUserDto" /> class.
        /// </summary>
        /// <param name="deleteDelay">deleteDelay</param>
        [JsonConstructor]
        public SystemConfigUserDto(int deleteDelay)
        {
            DeleteDelay = deleteDelay;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets DeleteDelay
        /// </summary>
        [JsonPropertyName("deleteDelay")]
        public int DeleteDelay { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SystemConfigUserDto {\n");
            sb.Append("  DeleteDelay: ").Append(DeleteDelay).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DeleteDelay (int) minimum
            if (this.DeleteDelay < (int)1)
            {
                yield return new ValidationResult("Invalid value for DeleteDelay, must be a value greater than or equal to 1.", new [] { "DeleteDelay" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SystemConfigUserDto" />
    /// </summary>
    public class SystemConfigUserDtoJsonConverter : JsonConverter<SystemConfigUserDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="SystemConfigUserDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SystemConfigUserDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> deleteDelay = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "deleteDelay":
                            deleteDelay = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!deleteDelay.IsSet)
                throw new ArgumentException("Property is required for class SystemConfigUserDto.", nameof(deleteDelay));

            if (deleteDelay.IsSet && deleteDelay.Value == null)
                throw new ArgumentNullException(nameof(deleteDelay), "Property is not nullable for class SystemConfigUserDto.");

            return new SystemConfigUserDto(deleteDelay.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SystemConfigUserDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="systemConfigUserDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SystemConfigUserDto systemConfigUserDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, systemConfigUserDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SystemConfigUserDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="systemConfigUserDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SystemConfigUserDto systemConfigUserDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("deleteDelay", systemConfigUserDto.DeleteDelay);
        }
    }
}
