// <auto-generated>
/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SystemConfigMetadataDto
    /// </summary>
    public partial class SystemConfigMetadataDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SystemConfigMetadataDto" /> class.
        /// </summary>
        /// <param name="faces">faces</param>
        [JsonConstructor]
        public SystemConfigMetadataDto(SystemConfigFacesDto faces)
        {
            Faces = faces;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Faces
        /// </summary>
        [JsonPropertyName("faces")]
        public SystemConfigFacesDto Faces { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SystemConfigMetadataDto {\n");
            sb.Append("  Faces: ").Append(Faces).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SystemConfigMetadataDto" />
    /// </summary>
    public class SystemConfigMetadataDtoJsonConverter : JsonConverter<SystemConfigMetadataDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="SystemConfigMetadataDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SystemConfigMetadataDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<SystemConfigFacesDto?> faces = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "faces":
                            faces = new Option<SystemConfigFacesDto?>(JsonSerializer.Deserialize<SystemConfigFacesDto>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!faces.IsSet)
                throw new ArgumentException("Property is required for class SystemConfigMetadataDto.", nameof(faces));

            if (faces.IsSet && faces.Value == null)
                throw new ArgumentNullException(nameof(faces), "Property is not nullable for class SystemConfigMetadataDto.");

            return new SystemConfigMetadataDto(faces.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SystemConfigMetadataDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="systemConfigMetadataDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SystemConfigMetadataDto systemConfigMetadataDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, systemConfigMetadataDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SystemConfigMetadataDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="systemConfigMetadataDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SystemConfigMetadataDto systemConfigMetadataDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (systemConfigMetadataDto.Faces == null)
                throw new ArgumentNullException(nameof(systemConfigMetadataDto.Faces), "Property is required for class SystemConfigMetadataDto.");

            writer.WritePropertyName("faces");
            JsonSerializer.Serialize(writer, systemConfigMetadataDto.Faces, jsonSerializerOptions);
        }
    }
}
