// <auto-generated>
/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// VersionCheckStateResponseDto
    /// </summary>
    public partial class VersionCheckStateResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VersionCheckStateResponseDto" /> class.
        /// </summary>
        /// <param name="checkedAt">checkedAt</param>
        /// <param name="releaseVersion">releaseVersion</param>
        [JsonConstructor]
        public VersionCheckStateResponseDto(string? checkedAt = default, string? releaseVersion = default)
        {
            CheckedAt = checkedAt;
            ReleaseVersion = releaseVersion;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CheckedAt
        /// </summary>
        [JsonPropertyName("checkedAt")]
        public string? CheckedAt { get; set; }

        /// <summary>
        /// Gets or Sets ReleaseVersion
        /// </summary>
        [JsonPropertyName("releaseVersion")]
        public string? ReleaseVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VersionCheckStateResponseDto {\n");
            sb.Append("  CheckedAt: ").Append(CheckedAt).Append("\n");
            sb.Append("  ReleaseVersion: ").Append(ReleaseVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="VersionCheckStateResponseDto" />
    /// </summary>
    public class VersionCheckStateResponseDtoJsonConverter : JsonConverter<VersionCheckStateResponseDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="VersionCheckStateResponseDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override VersionCheckStateResponseDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> checkedAt = default;
            Option<string?> releaseVersion = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "checkedAt":
                            checkedAt = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "releaseVersion":
                            releaseVersion = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!checkedAt.IsSet)
                throw new ArgumentException("Property is required for class VersionCheckStateResponseDto.", nameof(checkedAt));

            if (!releaseVersion.IsSet)
                throw new ArgumentException("Property is required for class VersionCheckStateResponseDto.", nameof(releaseVersion));

            return new VersionCheckStateResponseDto(checkedAt.Value!, releaseVersion.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="VersionCheckStateResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="versionCheckStateResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, VersionCheckStateResponseDto versionCheckStateResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, versionCheckStateResponseDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="VersionCheckStateResponseDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="versionCheckStateResponseDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, VersionCheckStateResponseDto versionCheckStateResponseDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (versionCheckStateResponseDto.CheckedAt != null)
                writer.WriteString("checkedAt", versionCheckStateResponseDto.CheckedAt);
            else
                writer.WriteNull("checkedAt");

            if (versionCheckStateResponseDto.ReleaseVersion != null)
                writer.WriteString("releaseVersion", versionCheckStateResponseDto.ReleaseVersion);
            else
                writer.WriteNull("releaseVersion");
        }
    }
}
